### Recuperar todas las películas
GET http://localhost:1234/products

### Recuperar una película por id
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=ACTION

### Crear articulo
POST http://localhost:1234/products
Content-Type: application/json

{
        "sql": "SELECT * FROM products",
        "title": "Mochila 10",
        "price": 109,
        "description": "La mochila perfecta para el día a día y los paseos por el bosque.",
        "category": "ropa de hombre",
        "image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        "rating": {
            "rate": 4,
            "count": 120
        }
}

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather 2",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

#### Online Create
POST https://rest-api-deploy-76t2-dev.fl0.io/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una película
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 2022
}


### update 
PATCH http://localhost:1234/movies/70a5b5e1-4b0a-4c5d-a729-2e79a2e1388e
Content-Type: application/json

{
  "title": "Mochila 5 updated"
}

### delete
DELETE http://localhost:1234/products/8175b16c-20bb-4f2c-9274-b8e89d06bcf4

### remoto
POST https://rest-api-deploy-76t2-dev.fl0.io/products
Content-Type: application/json

{
        "sql": "SELECT * FROM products",
        "title": "Remera para hombre entallada casual premium",
        "price": 22,
        "description": "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
        "category": "ropa de hombre",
        "image": "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
        "rating": {
            "rate": 4,
            "count": 59
        }
}